### PR TITLE
chore: Update sliceselector to match the rfc

### PR DESCRIPTION
**Pull request by He-Pin**
Motivation:
Update the slice selector to match the rfc

https://datatracker.ietf.org/doc/html/rfc9535#section-2.3.4.2.2

### CODE REVIEW

**Comment by gregsdennis** [comment]
@He-Pin Have you run the tests?

Also, please open an issue to discuss changes before submitting a PR.  It saves you work in the end.

**Comment by gregsdennis** [comment]
The current tests pass, but I'd be interested whether you can create a test that doesn't pass that your change fixes.  Otherwise, I'm inclined to leave it as is.

**Comment by He-Pin** [comment]
image

@gregsdennis I will do after work with a local IDE:)

**Comment by gregsdennis** [comment]
That's fine, but it works as is, and it was finicky to get working for some reason.  So unless there's a case for which the current code fails, I'm inclined to not mess with it.

**Comment by gregsdennis** [comment]
@He-Pin are you going to continue with this?  Otherwise, I'm going to close it.

**Comment by He-Pin** [comment]
I can try it this weekend

**Pull request closed without merging**
