### PR TITLE
fix: FunctionValueExpressionParser should support NodeListFunction

### PR DESCRIPTION
**Pull request by He-Pin**
Motivation:
Make FunctionValueExpressionParser support NodelistFunctionDefinition too

### CODE REVIEW

**Comment by gregsdennis** [comment]
No, a nodelist is not a value.  This parser handles only functions which return values.

**Comment by He-Pin** [comment]
But it's been evaluated

**Comment by gregsdennis** [comment]
Add a test that fails without your change, please.  I don't think this is necessary.

**Comment by He-Pin** [comment]
Let me check the `noop` first.

**Comment by He-Pin** [comment]
I try to run parse `$[?count(noop(@.*))>0)]` but it fails,

**Comment by gregsdennis** [comment]
Okay.  Good.  Please create a test, show that it fails without your changes and then apply your changes to show that they fix the problem.

**Comment by gregsdennis** [comment]
Closing in favor of #835

**Pull request closed without merging**
