### PR TITLE
added backdoor for new schema spec versions

### PR DESCRIPTION
**Pull request by gregsdennis**
### Description

In order to support Graeae, a backdoor needs to be created to allow for registration of new spec versions.  This is only to be used if you know what you're doing.

### Links

Relates to https://github.com/gregsdennis/Graeae/issues/5

### Checks

- [x] I have read and understand the [Code of Conduct](https://github.com/json-everything/json-everything/blob/master/CODE_OF_CONDUCT.md) and [Contribution Guidelines](https://github.com/json-everything/json-everything/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by gregsdennis** [comment]
@dotnet-policy-service agree

**Comment by gregsdennis** [comment]
I suppose I'm not technically @json-everything.  It's a bit weird signing a CLA to my own project.

@ChrisSfanos will it ask me this every time, or does it remember?

**Comment by gregsdennis** [comment]
Crap... forgot to update the version...

**Comment by ChrisSfanos** [comment]
> I suppose I'm not technically @json-everything. It's a bit weird signing a CLA to my own project.
> 
> @ChrisSfanos will it ask me this every time, or does it remember? (Edit... looks like it remembers.)

You only sign it one time

**Pull request merged**
